import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/Providers";
import Navbar from "@/components/NavBar";
import Search from "@/components/Search";
import StoreProvider from "@/store/StoreProvider";

const mons = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IMDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mons.className}>
        <StoreProvider>
          <Providers>
            <Header />
            <Navbar />
            <Search />
            {children}
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
